#**August 28, 2023**



  A collection of modules that are linked together is also known as a Python library. It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
v=np.zeros(10) # will print 10 zeros
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print('%d bytes' % (v.size * v.itemsize)) #shows memory of above values

80 bytes


In [ ]:
v=np.zeros(10)
v[4] = 1  #replacing the value of 0 to 1 on 4th index.
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
v = np.arange(10,20)
print(v) # It'll print vector of 10 values starting 10....In numpy, we call technically vector or ndarray to index.

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
v = np.arange(10,50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
v = np.arange(10,50)
print(v)
print(type(v))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


In [ ]:
v = np.arange(50)
print(v)

v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
v = np.arange (9).reshape(3,3) # when there are 2 square brackets starting and end, it is 2 dimentional data....with 3 square brackets, it is 3D data.
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
nz = np.nonzero([1,0,0,2,0,0,3,0,0,0,4,0,0,0,0,0,5,0,0,0,0,0,0,6]) # prnting index of non-zero values
print(nz)

(array([ 0,  3,  6, 10, 16, 23]),)


In [ ]:
v = np.eye(5) #prints 5x5 values
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
v = np.random.random() # prints random numbers from 0 to 1.
print(v)

0.0074997636773450616


In [ ]:
v = np.random.random((10,10)) #(10,10) is 2 dimensional value
print(v)

[[0.65011809 0.98385313 0.66101475 0.21342821 0.4120583  0.72145174
  0.48942141 0.35302121 0.74598412 0.8677825 ]
 [0.15553226 0.53108834 0.35493668 0.30988738 0.32311694 0.79664101
  0.7646885  0.8979651  0.0525405  0.3408978 ]
 [0.13417695 0.86037739 0.30758932 0.62441503 0.34188417 0.07690669
  0.53915066 0.92996091 0.52273832 0.840599  ]
 [0.12634204 0.96344969 0.62943584 0.31920926 0.04862387 0.17916053
  0.15422556 0.0465567  0.95014621 0.90747614]
 [0.30512934 0.15699454 0.81158436 0.3851085  0.18628636 0.36744336
  0.67317029 0.52602783 0.92175799 0.62679694]
 [0.6759109  0.8072511  0.41576031 0.21570185 0.28134442 0.71051205
  0.80914092 0.55924985 0.39778648 0.49579676]
 [0.93780606 0.23093158 0.91565587 0.37891197 0.66839327 0.65289983
  0.16628567 0.94755393 0.830289   0.84824859]
 [0.51339577 0.76246774 0.00981029 0.63718623 0.02063687 0.79520035
  0.87614175 0.67377304 0.85588064 0.03829515]
 [0.77729949 0.09782028 0.74259257 0.79673317 0.40339304 0.02139155
  0.18103925

In [ ]:
v = np.random.random((2,3,4)) #2 rows with 3 dimensional array...inside are 4 values
print(v)

[[[0.84435293 0.77465943 0.18598535 0.24091834]
  [0.00195991 0.86767358 0.36893046 0.94491043]
  [0.62761083 0.41724757 0.50818344 0.82311895]]

 [[0.82052174 0.50641255 0.22399155 0.25846312]
  [0.56471063 0.50646953 0.87312125 0.7425906 ]
  [0.64972896 0.51781222 0.354862   0.05276289]]]


In [ ]:
v = np.random.random((2,2,2)) # 2rows, 2d, 2values
print(v)

[[[0.22377491 0.78417168]
  [0.65997638 0.61327569]]

 [[0.32711242 0.92898104]
  [0.41387411 0.4940644 ]]]


In [ ]:
v = np.random.random((2,4,3))
print(v)

[[[0.44436105 0.36549384 0.81449188]
  [0.15880353 0.47745695 0.235007  ]
  [0.89944133 0.85284219 0.79460091]
  [0.66017821 0.74334461 0.22165174]]

 [[0.26909153 0.20571451 0.06691656]
  [0.38438346 0.74075301 0.36455399]
  [0.48014595 0.36392708 0.55126676]
  [0.72559256 0.65352231 0.8956135 ]]]


In [ ]:
v = np.random.random((10,10)) # random value always changes/generates different values on every run
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9777538073027332 0.003537373137144195


In [ ]:
v = np.random.random(30) #prints mean of 30 random values
v_mean = v.mean()
print(v_mean)

0.4819535877242592


In [ ]:
v = np.ones((10,10))
print(v)

v[1:-1,1:-1] = 0
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#create matrix of zeros and convert inner values to 1
v = np.zeros((10,10))
print(v)
print (" ")
v[1:-1,1:-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
v = np.ones((5,5))
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
v = np.ones((5,5))
print(v)
v = np.pad(v, pad_width=1, mode='constant', constant_values=9)
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [ ]:
np.nan #nan is not a no. (null).....nothing....no zero, no -1/+1.....don't compare nan with zero

nan

In [ ]:
print(0 * np.nan) #nan
print (np.nan == np.nan) #false
print (np.inf > np.nan) #false
print (np.nan - np.nan) # nan
print (0.3 == 3*0.1) #false

nan
False
False
nan
False


In [ ]:
3*0.10

0.30000000000000004

In [ ]:
print(np.nan/1)
print(1/np.nan)
print(np.nan + np.nan)
print(np.nan > 0)
print (0 < np.nan)
print (np.nan > 1)
print (1 > np.nan)

nan
nan
nan
False
False
False
False


In [ ]:
#create 5x5 matrix with values 1,2,3,4 under diagonal
z=np.diag(1+np.arange(4),k=-1) #k=-1 skips last column
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
# Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Normalize a 5x5 random matrix

Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.97861925 0.25855476 0.12410122 0.14503381 0.99157646]
 [0.01078642 0.84144981 0.65365595 0.78683601 0.78696094]
 [0.99735138 0.90994324 0.8902674  0.27250021 0.43764693]
 [0.86503091 0.60819942 1.         0.22729568 0.56194764]
 [0.10174994 0.         0.84113758 0.42270224 0.12276825]]


In [ ]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-62-5043add1dd64>:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [ ]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [ ]:
# What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# What are the result of the following expressions?

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-66-ef234b2a6acc>:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-66-ef234b2a6acc>:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [ ]:
# How to round away from zero a float array ?

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  1.  -7.  -9.  -5.  -3. -10.  -2.   2.   5.   4.]


In [ ]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 5 9]


In [ ]:
# Is the following expressions true?

np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-69-4cdd710269fc>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
# How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('yesterday:',yesterday, 'today:',today, 'tomorrow:',tomorrow)

yesterday: 2023-09-04 today: 2023-09-05 tomorrow: 2023-09-06


In [ ]:
# How to get all the dates corresponding to the month of July 2016?

Z = np.arange('2023-07', '2023-08', dtype='datetime64[D]')
print(Z)

['2023-07-01' '2023-07-02' '2023-07-03' '2023-07-04' '2023-07-05'
 '2023-07-06' '2023-07-07' '2023-07-08' '2023-07-09' '2023-07-10'
 '2023-07-11' '2023-07-12' '2023-07-13' '2023-07-14' '2023-07-15'
 '2023-07-16' '2023-07-17' '2023-07-18' '2023-07-19' '2023-07-20'
 '2023-07-21' '2023-07-22' '2023-07-23' '2023-07-24' '2023-07-25'
 '2023-07-26' '2023-07-27' '2023-07-28' '2023-07-29' '2023-07-30'
 '2023-07-31']


In [ ]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
# Extract the integer part of a random array using 5 different methods?

Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 2. 7. 5. 2. 1. 8. 4. 7. 5.]
[7. 2. 7. 5. 2. 1. 8. 4. 7. 5.]
[7. 2. 7. 5. 2. 1. 8. 4. 7. 5.]
[7 2 7 5 2 1 8 4 7 5]
[7. 2. 7. 5. 2. 1. 8. 4. 7. 5.]


In [ ]:
# Create a 5x5 matrix with row values ranging from 0 to 4

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
# Create a random vector of size 10 and sort it

Z = np.random.random(10)
Z.sort()
print(Z)

[0.00236842 0.02494172 0.10754202 0.13118445 0.1520588  0.22472531
 0.38686572 0.53816739 0.90421175 0.95021902]


In [ ]:
# How to sum a small array faster than np.sum?

Z = np.arange(10)
np.add.reduce(Z)

45

In [ ]:
# Consider two random array A and B, check if they are equal?

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A, B)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

[0 1 0 0 1] [0 1 1 0 1]
False
False


In [ ]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates?

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.39713086 0.09578842 0.97883417 0.75359034 0.47659219 0.65680713
 0.24104581 0.35152637 0.71210538 1.3606944 ]
[0.42991449 1.03739045 0.2337566  1.2392638  0.36239934 1.06183029
 1.15487541 0.43452874 0.59792329 0.75886465]


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0?

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.28151616 0.70705408 0.6327191  0.         0.54603067 0.65871509
 0.49510597 0.7481701  0.11748941 0.65247308]


In [ ]:
# Create a structured array with x and y coordinates covering the [0,1]x[0,1] area?

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))?

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
# Print the minimum and maximum representable value for each numpy scalar type?

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
# How to find the closest value (to a given scalar) in a vector?

Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

82


In [ ]:
# How to convert a float (32 bits) array into an integer (32 bits) in place?

Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# What is the equivalent of enumerate for numpy arrays?

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
# How to sort an array by the nth column?

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 4 9]
 [5 5 9]
 [5 2 1]]
[[5 2 1]
 [2 4 9]
 [5 5 9]]


In [ ]:
# Find the nearest value from a given value in an array?

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5237257019254009


In [ ]:
# Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#**August 29, 2023**

In [ ]:
import numpy as np
lst1 = [11,22,33,44,55,66,77,88,99,110]
arr1 = np.array(lst1)
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
import numpy as np
lst1 = [11,22,33,44,55,66,77,88,99,110]
arr1 = np.array(lst1)
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
set1 = {1,2,3,4,5,0,True,False,'Python','Programming'}
arr3 = np.array(set1)
arr3

array({0, 1, 2, 3, 4, 5, 'Python', 'Programming'}, dtype=object)

In [ ]:
dict1 = {'a':[1,2,3,4,5,0],'b':(True,False),'c':'Python','d':'Programming'}
arr4 = np.array(dict1)
arr4

array({'a': [1, 2, 3, 4, 5, 0], 'b': (True, False), 'c': 'Python', 'd': 'Programming'},
      dtype=object)

In [ ]:
str1 = 'Python Programming'
arr5 = np.array(str1)
print(arr5)

Python Programming


In [ ]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1d)
arr1d.ndim

[ 1  2  3  4  5  6  7  8  9 10]


1

In [ ]:
arr2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(arr2d)
arr2d.ndim

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [ ]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
print(arr3d)
arr3d.ndim

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([
    [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
    [[[11, 12, 13], [14, 15, 16]], [[11, 12, 13], [14, 15, 16]]]
    ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4
